version: "3.8"
services:
  db:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
  app:
    build: .
    command: yarn run dev
    ports:
      - 8080:8080
    environment:
      POSTGRES_HOST: db
      HOST: 0.0.0.0
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 5s
      retries: 3
    depends_on:
      - db
