service: pdf2qa-sls
frameworkVersion: "3"
useDotenv: true

plugins:
  - serverless-better-credentials
  - serverless-offline
  - serverless-esbuild
  - serverless-plugin-test-helper

package:
  patterns:
    - "!node_modules/**"
    - "!src/**"
    - "!terraform/**"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: eu-west-2

functions:
  ping:
    handler: ./src/lambda/ping.handler
    name: ping
    events:
      - http:
          path: /
          method: get
  authorizer:
    handler: ./src/lambda/authorizer.handler
    name: authorizer
    events:
      - http:
          path: /authorizer
          method: post
  uploadPdf:
    handler: ./src/lambda/uploadPdf.handler
    name: uploadPdf
    events:
      - http:
          path: /upload-pdf
          method: post
          authorizer:
            name: authorizer
            resultTtlInSeconds: 0
            identitySource: method.request.header.cookie
            type: token
